import Link from 'next/link';
import { FaRocketchat } from 'react-icons/fa';

const HomePage = (): JSX.Element => {
  return (
    <div>
      <header className="header">
        <div className="container header-container">
          <Link href="/">
            <a className="logo">
              <FaRocketchat />
              <p>Chat-Center</p>
            </a>
          </Link>
          <nav>
            <Link href="register">
              <a className="sing-up-button">Registrate</a>
            </Link>

            <Link href="login">
              <a className="login-button">Iniciar sesión</a>
            </Link>
          </nav>
        </div>
      </header>
      <main className="main">
        <div className="container">
          <div className="description">
            <h1>Efficiently manage the needs of your clients.</h1>
            <p>
              A CRM based on messages that allows your companies to give support
              to customers and suppliers in a fast way and is also a tool for
              promotion and sales.
            </p>
          </div>
          <img
            src="https://cdn.pixabay.com/photo/2016/10/26/16/45/rock-1771916_960_720.jpg"
            alt="chat-center"
          />
        </div>
      </main>
      <section className="features">
        <div className="container">
          <h2>Features</h2>
          <div>
            <img
              src="https://cdn.pixabay.com/photo/2016/10/26/16/45/rock-1771916_960_720.jpg"
              alt="chat-center"
            />
          </div>
          <div className="list-features">
            <h3>With ChatCenter:</h3>
            <ul>
              <li>Manage service agents to serve customers.</li>
              <li>
                You can manage your customers, service tickets and
                conversations.
              </li>
              <li>
                Dynamically assign case loads based on Agent availability.
              </li>
              <li>
                Generate a log of the chats generated by each service ticket and
                thus make a follow-up.
              </li>
              <li>Generation of chat and agent activity reports.</li>
            </ul>
          </div>
        </div>
      </section>
      <footer className="footer">
        <div className="container">
          <p>
            Condiciones de uso - Política de privacidad - Política de cookies ©
            ChatCenter 2020
          </p>
        </div>
      </footer>
      <style jsx>{`
        .footer p {
          font-size: 16px;
          text-align: center;
          color: #fff;
        }
        .footer {
          padding: 30px;
          background-color: #4f9a94;
        }
        .features .container div img {
          width: 100%;
        }
        .features .container {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          grid-template-rows: auto 1fr;
          gap: 20px;
        }
        .list-features h3 {
          font-size: 28px;
          margin-bottom: 20px;
        }
        .list-features ul {
          list-style: none;
        }
        .list-features li {
          font-size: 21px;
          margin-bottom: 20px;
        }
        .features h2 {
          grid-column: 1 / 3;
          font-size: 28px;
          text-align: center;
        }
        .features {
          padding: 100px 30px;
        }
        .container {
          width: 100%;
          max-width: 1200px;
          margin: auto;
        }
        .main {
          padding: 100px 30px;
          background-color: #f2f2f2;
        }
        .main .container {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
        }
        .description {
          width: 50%;
          font-size: 28px;
        }
        .description h1 {
          margin-top: 0;
          margin-bottom: 30px;
        }
        .description p {
          font-size: 28px;
        }
        .description + img {
          width: 40%;
        }
        .header {
          background-color: #00695c;
          padding: 20px;
        }
        .header-container {
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .logo {
          display: flex;
          justify-content: center;
          align-items: center;
          color: white;
          text-decoration: none;
        }
        .sing-up-button {
          background-color: #80cbc4;
          border-radius: 10px;
          padding: 10px 20px;
          margin-right: 30px;
          text-decoration: none;
          color: black;
        }
        .login-button {
          border: solid 2px #80cbc4;
          border-radius: 10px;
          padding: 10px 20px;
          text-decoration: none;
          color: white;
        }
      `}</style>
    </div>
  );
};

export default HomePage;
